# Generated by Django 6.0.1 on 2026-04-10 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_states', to='orders.orderstate', verbose_name='وضعیت سفارش'),
        ),
    ]
