# Generated by Django 6.0.1 on 2026-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_order_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت کالا در فاکتور'),
        ),
    ]
