# Generated by Django 6.0.1 on 2026-03-27 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 27, 13, 27, 7, 534251, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پرداخت'),
        ),
    ]
