# Generated by Django 6.0.1 on 2026-04-17 10:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_alter_payment_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 17, 10, 23, 38, 84106, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پرداخت'),
        ),
    ]
