# Generated by Django 6.0.1 on 2026-04-18 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_payment_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ پرداخت'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 18, 11, 41, 20, 210314, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پرداخت'),
        ),
    ]
