# Generated by Django 6.0.4 on 2026-04-22 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_alter_payment_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 22, 18, 59, 18, 665907, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پرداخت'),
        ),
    ]
