# Generated by Django 6.0.1 on 2026-03-22 12:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_alter_customer_image_name'),
        ('orders', '0003_paymenttype_order_description_order_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_date', models.DateTimeField(default=datetime.datetime(2026, 3, 22, 12, 51, 10, 6333, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پرداخت')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش پرداخت')),
                ('amount', models.IntegerField(verbose_name='مبلغ پرداخت')),
                ('description', models.TextField(verbose_name='توضیخات پرداخت')),
                ('is_finaly', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='کد وضعیت درگاه پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='کد پیگیری پرداخت')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_customer', to='accounts.customer', verbose_name='مشتری')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_order', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'managed': True,
            },
        ),
    ]
