# Generated by Django 6.0.1 on 2026-04-04 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='register_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 4, 18, 33, 5, 284300, tzinfo=datetime.timezone.utc), verbose_name='تاریخ پرداخت'),
        ),
    ]
