# Generated by Django 6.0.4 on 2026-05-18 13:11

import ckeditor_uploader.fields
import django.db.models.deletion
import utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0033_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان دسته\u200cبندی')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی بلاگ',
                'verbose_name_plural': 'دسته بندی\u200cهای بلاگ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='اسلاگ')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='محتوا')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=utils.FileUpload.upload_to, verbose_name='تصویر مقاله')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('register_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('blog_group', models.ManyToManyField(blank=True, related_name='posts', to='blogs.bloggroup', verbose_name='دسته بندی\u200cها')),
                ('related_products', models.ManyToManyField(blank=True, related_name='related_blog_posts', to='products.product', verbose_name='محصولات مرتبط')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست\u200cهای بلاگ',
                'ordering': ['-published_date', '-register_date'],
            },
        ),
    ]
