# Generated by Django 6.0.1 on 2026-04-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('page_type', models.CharField(choices=[('about', 'درباره ما'), ('contact', 'تماس با ما'), ('rules', 'قوانین و مقررات')], max_length=20, verbose_name='نوع صفحه')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'صفحه ثابت',
                'verbose_name_plural': 'صفحات ثابت',
                'managed': True,
            },
        ),
    ]
