"""
Django settings for center project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(dotenv_path=BASE_DIR / '.env')   # .env کردن load

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise ValueError("SECRET_KEY not set in environment variables")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "True"
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG  # کار کند https فقط در
CSRF_COOKIE_SECURE = not DEBUG  # کار کند https فقط در
print("DEBUG =", DEBUG)

SESSION_COOKIE_HTTPONLY = True   # نتوانند کوکی سشن کاربر را هک کنند از نظر امنیتی این خط حیاطیه (XSS) برای سایت تجاری باید این خط حتما اضافه شه تا اسکریپت‌های مخرب
# SECURE_SSL_REDIRECT = not DEBUG  # https وارد بشه اتومات بره پرتوکل http فعال شد از کامنت در بیار این به این معنیه که اگر کسی با https وقتی
CSRF_COOKIE_HTTPONLY = False


# فقط بعد از داشتن دامنه واقعی
# CSRF_TRUSTED_ORIGINS = [
#     "https://example.com",
#     "https://www.example.com",
# ]


# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
# ALLOWED_HOSTS = ['example.com', 'www.example.com']   # دامنه اصلی سایت رو اینجا قرار بده و از کامنت در بیار و بالایی رو کامنت کن چون اون بالایی برای لوکاله deploy بعد از خرید دامنه و

# امنیت هدرها
SECURE_BROWSER_XSS_FILTER = True  # در مرورگر (XSS) فعال کردن فیلتر ضدِ تزریق کدهای مخرب
SECURE_CONTENT_TYPE_NOSNIFF = True  # جلوگیری از حدس زدن نوع فایل توسط مرورگر (مانع اجرای فایل‌های مخرب بجای عکس می‌شود)
X_FRAME_OPTIONS = 'DENY'  # اجازه نمی‌دهد سایت شما داخل سایت‌های دیگر (مثل آی‌فریم) نمایش داده شود تا جلوی کلیک‌دزدی گرفته شود

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "storages",             # آپلود تصاویر AWS S3
    "phonenumber_field",                  # شماره موبایل معتبر (ایران+جهان)
    "django_render_partial",
    'django_cleanup.apps.CleanupConfig',   # حذف خودکار فایل‌های بلااستفاده مثل تصاویر
    "django_admin_listfilter_dropdown",
    "rest_framework",    # API
    "django_filters",     # فیلتر کردن محصولات در سایت
    "import_export",     # خروجی CSV/Excel برای ادمین
    "ckeditor",
    "axes",
    "apps.main.apps.MainConfig",
    "apps.accounts.apps.AccountsConfig",
    "apps.products.apps.ProductsConfig",
    "apps.orders.apps.OrdersConfig",
    "apps.discounts.apps.DiscountsConfig",
    "apps.payments.apps.PaymentsConfig",
    "apps.warehouses.apps.WarehousesConfig",
    "apps.comment_scoring_favorites.apps.CommentScoringFavoritesConfig",
    "apps.search.apps.SearchConfig",
    "apps.test_api.apps.TestApiConfig",
    "apps.pages.apps.PagesConfig",
    "apps.blogs.apps.BlogsConfig",
]

# تنظیمات Axes
# (تست کردن رمزهای مختلف از سمت هکر) Brute-force برای جلوگیری از حملات
# ضروریه و اضافه کردن این چند خط بعد از نصبش باید نوشتخ شه django-axes کتابخانه
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesBackend',
    'django.contrib.auth.backends.ModelBackend',
]
AXES_FAILURE_LIMIT = 6 # بعد از 6 بار تلاش اشتباه مسدود شود
AXES_COOLOFF_TIME = 1  # مسدودی به مدت ۱ ساعت

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middlewares.middlewares.RequestMiddleware",
]

ROOT_URLCONF = "center.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.main.views.media_admin",
                "apps.products.context_processor.navbar_categories",
                "apps.blogs.context_processors.blog_sidebar",
            ],
        },
    },
]

WSGI_APPLICATION = "center.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": "localhost",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "fa"
TIME_ZONE = "Asia/Tehran"

USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"),)

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'accounts.CustomUser'

CKEDITOR_STORAGE_BACKEND = 'django.core.files.storage.FileSystemStorage'
CKEDITOR_UPLOAD_PATH = 'images/ckeditor/upload_files/'
CKEDITOR_CONFIGS = {
    'admin_full': {
        'skin': 'moono',
        'toolbar': 'Full',
        'toolbar_Full': [
            {'name': 'document', 'items': ['Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates']},
            {'name': 'clipboard', 'items': ['Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo']},
            {'name': 'editing', 'items': ['Find', 'Replace', '-', 'SelectAll', 'Scayt']},
            {'name': 'forms',
            'items': ['Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton',
                        'HiddenField']},
            '/',
            {'name': 'basicstyles',
            'items': ['Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'RemoveFormat', 'CopyFormatting']},
            {'name': 'paragraph',
            'items': ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-',
                        'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl',
                        'Language']},
            {'name': 'links', 'items': ['Link', 'Unlink', 'Anchor']},
            {'name': 'insert',
                'items': ['Image', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe', 'Embed', 'Flash']},
            '/',
            {'name': 'styles', 'items': ['Styles', 'Format', 'Font', 'FontSize']},
            {'name': 'colors', 'items': ['TextColor', 'BGColor']},
            {'name': 'tools', 'items': ['Maximize', 'ShowBlocks', 'Preview', 'About', 'RemoveFormat']},
        ],
        'height': 400,
        'width': '100%',
        'toolbarCanCollapse': True,
        'tabSpaces': 4,
        'extraPlugins': ','.join([
            'uploadimage',
            'div',
            'autolink',
            'autoembed',
            'embedsemantic',
            'autogrow',
            'widget',
            'lineutils',
            'clipboard',
            'dialog',
            'dialogui',
            'elementspath',
            'mathjax',
            'codesnippet',
            'devtools',
            'embed',
            'notification',
        ]),
        'filebrowserWindowHeight': 725,
        'filebrowserWindowWidth': 940,
        'mathJaxLib': '//cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-MML-AM_CHTML',
    }
}


# ===== SMS.IR =====
SMS_IR_API_KEY = os.getenv('SMS_IR_API_KEY')
FROM_NUMBER = os.getenv('FROM_NUMBER', '30002128098428')
# SMS_IR_VERIFY_TEMPLATE_ID = int(os.getenv("SMS_IR_VERIFY_TEMPLATE_ID", "0"))
SMS_IR_VERIFY_TEMPLATE_ID = os.getenv("SMS_IR_VERIFY_TEMPLATE_ID")


# ===== ZARINPAL =====
ZARINPAL_MERCHANT_ID = os.getenv('ZARINPAL_MERCHANT_ID')
# SANDBOX = True
SANDBOX=False   # جای اون مرچنت آی دی که تستی هست بزار .env واقعی این کامنت رو بردار و خط بالا رو کامنت کن و مرچنت آی دی واقعی رو توفایل MERCHANT_ID بعد از گرفتن

# pip install redis django-redis بعد از نصب
# Redis ذخیره داده‌های موقت پروژه مثل کد تایید در
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv('REDIS_URL'),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "TIMEOUT": 300,
    }
}
