# Generated by Django 6.0.1 on 2026-04-12 14:37

import django.utils.timezone
import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title1', models.CharField(max_length=50, verbose_name='متن اسلایدر اول')),
                ('slider_title2', models.CharField(max_length=50, verbose_name='متن اسلایدر دوم')),
                ('slider_title3', models.CharField(max_length=50, verbose_name='متن اسلایدر سوم')),
                ('image_name', models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید')),
                ('slider_link', models.URLField(blank=True, null=True, verbose_name='لینک')),
                ('is_active', models.BooleanField(blank=True, default=True, verbose_name='وضعیت فعال/غیرفعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین به روز رسانی')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'managed': True,
            },
        ),
    ]
