# Generated by Django 6.0.1 on 2026-04-13 11:22

import utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='image_name',
            field=models.ImageField(upload_to=utils.FileUpload.upload_to, verbose_name='تصویر اسلاید'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متن اسلایدر اول'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متن اسلایدر دوم'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='slider_title3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='متن اسلایدر سوم'),
        ),
    ]
