# Generated by Django 6.0.1 on 2026-04-18 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=15, null=True, verbose_name='قیمت'),
        ),
    ]
